# Main configuration file for mkdocs generation of BIGTREETECH.org website

# Note that the build-translations.sh script expects a certain file
# layout.  See that script and the README file for more details.

# Site and directory configuration
site_name: BIGTREETECH documentation
repo_url: https://github.com/bigtreetech/docs
repo_name: bigtreetech/docs
edit_uri: blob/master/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

# Custom markdown dialect settings
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 6
  - attr_list
  - mdx_partial_gfm
  - mdx_truly_sane_lists
  - mdx_breakless_lists
plugins:
  search:
    lang: en
  mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs._biqumkdocs.mkdocs_hooks:transform"
  exclude:
    glob: "README.md"

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: img/BQ-BIQU.svg
  favicon: img/favicon.ico  
  icon:
    repo: fontawesome/brands/github
    alternate: material/web
  features:
      #- navigation.tabs
      #- navigation.expand
      - navigation.top
      # if enabled, the TOC doesn't work for some pages
      # - toc.integrate
      - search.suggest
      - search.highlight
      - search.share
  language: en
extra_css:
  - _biqumkdocs/css/extra.css

# Site usage statistics
# extra:
#   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#site-search-tracking
#   analytics:
#     provider: google
#     property: UA-138371409-1
#   # Language Selection
#   alternate:
#     - name: English
#       link: /
#       lang: en
    # Alternate language links automatically added here

# Navigation hierarchy (this should mimic the layout of Overview.md)
nav:
  - Motherboards:
    - SKR Series:
      - SKR MINI E3.md
    - Octopus Series:
      - Octopus.md
      - Octopus Pro.md
      - Octopus MAX EZ.md
    - Manta Series:
      - M4P.md
      - M5P.md
      - M8P.md
    - EBB Series:
      - EBB 36 CAN.md
      - EBB 42 CAN.md
      - EBB 2240 2209 CAN.md
      - EBB 2209 CAN RP2040.md
      - U2C.md
  - IOT:
    - CB1.md
    - PI4B.md
    - PAD7.md
    - KNOMI.md
    - KNOMI2.md
  - Displays:
    - TFT43-DIP.md
    - TFT35 E3.md
    - TFT35.md
    - TFT24.md
    - TFT35 SPI.md
    - HDMI5.md
    - HDMI7.md
  - Motor Drives:
    - TMC Series:
      - TMC2130.md
      - TMC5160.md
      - TMC2209.md
      - TMC2208.md
      - Tutorials.md
    - EZ Series:
      - EZ2130.md
      - EZ2208.md
      - EZ2225.md
      - EZ2226.md
      - EZ5160 Pro.md
      - EZDriver Connector.md
      - EZ2209.md
      - EZ2240.md
      - EZ31865.md
  - Software Tutorials:
    - Multiple 3D Printers.md
    - Software Configuration.md
    - Software Installation.md
    - EBB Series.md
    - libinput_calibration.md
